# https://render.com/docs/blueprint-spec
#
# TRICKY: We can’t include the environment group here
#         if we want to share it between blueprint instances
# envVarGroups:
# - name: dollyskettle-settings
#   envVars:
#     - key: GITHUB_USER_EMAIL
#       sync: false
#     - key: GITHUB_USER_NAME
#       sync: false
#     - key: GITHUB_REPOSITORY
#       sync: false
#
#   NOTE: This is for documentation purposes and isn’t supported by Render
#   secretFiles:
#     - fileName: .htpasswd
#       sync: false
#     - fileName: id_ed25519
#       sync: false
#     - fileName: id_ed25519.pub
#       sync: false
#     - fileName: known_hosts
#       sync: false
#
# - name: dollyskettle-remote-backup
#   envVars:
#     - key: WORDPRESS_ENVIRONMENT
#       value: remote-backup
#     - key: REMOTE_WORDPRESS_DB_HOST
#       sync: false
#     - key: REMOTE_WORDPRESS_DB_USER
#       sync: false
#     - key: REMOTE_WORDPRESS_DB_PASSWORD
#       sync: false
#     - key: REMOTE_WORDPRESS_DB_NAME
#       sync: false
#     - key: REMOTE_WORDPRESS_SSH_HOST
#       sync: false
#     - key: REMOTE_WORDPRESS_SSH_USER
#       sync: false
#     - key: REMOTE_WORDPRESS_SSH_PASSWORD
#       sync: false
#     - key: REMOTE_WORDPRESS_FILE_PATH
#       sync: false
#     - key: REMOTE_BACKUP_DEPLOY_HOOK
#       sync: false
#     - key: REMOTE_BACKUP_API_TOKEN
#       sync: false
#     - key: REMOTE_BACKUP_MYSQL_SERVICE_ID
#       sync: false
#     - key: REMOTE_BACKUP_WORDPRESS_SERVICE_ID
#       sync: false
#     - key: REMOTE_URL
#       sync: false
#     - key: REMOTE_URL_AUTHORIZATION_BASIC
#       sync: false
#     - key: REPLICA_DEPLOY_HOOK
#       sync: false
#     - key: REPLICA_API_TOKEN
#       sync: false
#     - key: REPLICA_MYSQL_SERVICE_ID
#       sync: false
#     - key: REPLICA_WORDPRESS_SERVICE_ID
#       sync: false
#     - key: REPLICA_URL
#       sync: false
#     - key: REPLICA_URL_AUTHORIZATION_BASIC
#       sync: false
#
# - name: dollyskettle-replica
#   envVars:
#     - key: WORDPRESS_ENVIRONMENT
#       value: replica
#     - key: BACKUP_STATUS_DEPLOY_HOOK
#       sync: false
#     - key: BACKUP_STATUS_API_TOKEN
#       sync: false
#     - key: BACKUP_STATUS_SERVICE_ID
#       sync: false
#
# - name: dollyskettle-publish
#   envVars:
#     - key: WORDPRESS_ENVIRONMENT
#       value: publish
#     - key: GITHUB_USER_EMAIL
#       sync: false
#     - key: GITHUB_USER_NAME
#       sync: false
#     - key: GITHUB_REPOSITORY
#       sync: false
#     - key: NETLIFY_SITE_ID
#       sync: false
#     - key: NETLIFY_AUTH_TOKEN
#       sync: false
#     - key: AUTHORIZATION_HEADER_VALUE
#       sync: false
#
#   NOTE: This is for documentation purposes and isn’t supported by Render
#   secretFiles:
#     - fileName: id_ed25519
#       sync: false
#     - fileName: id_ed25519.pub
#       sync: false
#     - fileName: known_hosts
#       sync: false
#
previewsEnabled: true
services:
- type: web
  name: dollyskettle-wordpress
  env: docker
  dockerfilePath: ./apache/Dockerfile
  dockerContext: ./apache
  initialDeployHook: "sh /usr/local/bin/wordpress-setup.sh"
  autoDeploy: false
  region: oregon
  plan: starter
  disk:
    name: www
    mountPath: /var/www
    sizeGB: 30
  envVars:
  - fromGroup: dollyskettle-settings
  - key: WORDPRESS_DB_HOST
    fromService:
      name: dollyskettle-mysql
      type: pserv
      property: host
  - key: WORDPRESS_DB_NAME
    fromService:
      name: dollyskettle-mysql
      type: pserv
      envVarKey: MYSQL_DATABASE
  - key: WORDPRESS_DB_USER
    fromService:
      name: dollyskettle-mysql
      type: pserv
      envVarKey: MYSQL_USER
  - key: WORDPRESS_DB_PASSWORD
    fromService:
      name: dollyskettle-mysql
      type: pserv
      envVarKey: MYSQL_PASSWORD
- type: pserv
  name: dollyskettle-mysql
  dockerfilePath: ./mysql/Dockerfile
  dockerContext: ./mysql
  env: docker
  autoDeploy: false
  region: oregon
  plan: starter
  disk:
    name: mysql
    mountPath: /var/lib/mysql
    sizeGB: 1
  envVars:
  - key: MYSQL_DATABASE
    value: wordpress
  - key: MYSQL_USER
    value: wordpress
  - key: MYSQL_PASSWORD
    generateValue: true
  - key: MYSQL_ROOT_PASSWORD
    generateValue: true
# A Python cron job that runs at 5 a.m. UTC
- type: cron
  name: dollyskettle-backup
  env: python
  region: oregon
  schedule: "0 5 * * *"
  startCommand: ./backup/start.sh
  envVars:
  - fromGroup: dollyskettle-settings
- type: web
  name: dollyskettle-backup-status
  env: static
  autoDeploy: false
  buildCommand: sh ./backup/test.sh
  staticPublishPath: ./backup-test-results
  envVars:
  - fromGroup: dollyskettle-settings
- type: worker
  name: dollyskettle-publish
  env: docker
  dockerfilePath: ./publish/Dockerfile
  dockerContext: ./publish
  initialDeployHook: "sh /usr/local/bin/setup.sh"
  autoDeploy: false
  region: oregon
  plan: starter
  disk:
    name: root
    mountPath: /root
    sizeGB: 30
