# https://render.com/docs/blueprint-spec
#
# TRICKY: We can’t include the environment group here
#         if we want to share it between blueprint instances
# envVarGroups:
# - name: dollyskettle-settings
#   envVars:
#     - key: GITHUB_USER_EMAIL
#       sync: false
#     - key: GITHUB_USER_NAME
#       sync: false
#     - key: GITHUB_REPOSITORY
#       sync: false
#
#   NOTE: This is for documentation purposes and isn’t supported by Render
#   secretFiles:
#     - fileName: .htpasswd
#       sync: false
#     - fileName: id_ed25519
#       sync: false
#     - fileName: id_ed25519.pub
#       sync: false
#     - fileName: known_hosts
#       sync: false
#
previewsEnabled: true
services:
- type: web
  name: dollyskettle-wordpress
  env: docker
  dockerfilePath: ./apache/Dockerfile
  dockerContext: ./apache
  initialDeployHook: "sh /usr/local/bin/wordpress-setup.sh"
  dockerCommand: "sh /usr/local/bin/wordpress-reset.sh"
  autoDeploy: true
  region: oregon
  plan: starter
  disk:
    name: wordpress
    mountPath: /var/www
    sizeGB: 25
  envVars:
  - fromGroup: dollyskettle-settings
  - key: WORDPRESS_DB_HOST
    fromService:
      name: dollyskettle-mysql
      type: pserv
      property: host
  - key: WORDPRESS_DB_NAME
    fromService:
      name: dollyskettle-mysql
      type: pserv
      envVarKey: MYSQL_DATABASE
  - key: WORDPRESS_DB_USER
    fromService:
      name: dollyskettle-mysql
      type: pserv
      envVarKey: MYSQL_USER
  - key: WORDPRESS_DB_PASSWORD
    fromService:
      name: dollyskettle-mysql
      type: pserv
      envVarKey: MYSQL_PASSWORD
- type: pserv
  name: dollyskettle-mysql
  dockerfilePath: ./mysql/Dockerfile
  dockerContext: ./mysql
  env: docker
  autoDeploy: false
  region: oregon
  plan: starter
  disk:
    name: mysql
    mountPath: /var/lib/mysql
    sizeGB: 1
  envVars:
  - key: MYSQL_DATABASE
    value: wordpress
  - key: MYSQL_USER
    value: wordpress
  - key: MYSQL_PASSWORD
    generateValue: true
  - key: MYSQL_ROOT_PASSWORD
    generateValue: true
