services:
- type: pserv
  name: dollyskettle-mysql
  plan: starter
  env: docker
  repo: https://github.com/jimthoburn/dollyskettle-mysql.git
  disk:
    name: mysql
    mountPath: /var/lib/mysql
    sizeGB: 1
  envVars:
  - fromGroup: dollyskettle-env

envVarGroups:
- name: dollyskettle-env
  envVars:
  - key: MYSQL_DATABASE
    value: mysql
  - key: MYSQL_USER
    value: mysql
  - key: MYSQL_PASSWORD
    generateValue: true
  - key: MYSQL_ROOT_PASSWORD
    generateValue: true
