services:
- type: web
  name: dollyskettle-wordpress
  repo: https://github.com/jimthoburn/dollyskettle-wordpress.git
  env: docker
  plan: starter
  disk:
    name: wordpress
    mountPath: /var/www/html
    sizeGB: 10
  envVars:
  - key: WORDPRESS_DB_HOST
    fromService:
      name: dollyskettle-mysql
      type: pserv
      property: host
  - key: WORDPRESS_DB_NAME
    fromService:
      name: dollyskettle-mysql
      type: pserv
      envVarKey: MYSQL_DATABASE
  - key: WORDPRESS_DB_USER
    fromService:
      name: dollyskettle-mysql
      type: pserv
      envVarKey: MYSQL_USER
  - key: WORDPRESS_DB_PASSWORD
    fromService:
      name: dollyskettle-mysql
      type: pserv
      envVarKey: MYSQL_PASSWORD
- type: pserv
  name: dollyskettle-mysql
  repo: https://github.com/jimthoburn/dollyskettle-mysql.git
  env: docker
  plan: starter
  disk:
    name: mysql
    mountPath: /var/lib/mysql
    sizeGB: 1
  envVars:
  - key: MYSQL_DATABASE
    value: mysql
  - key: MYSQL_USER
    value: mysql
  - key: MYSQL_PASSWORD
    generateValue: true
  - key: MYSQL_ROOT_PASSWORD
    generateValue: true
