services:
- type: web
  name: dollyskettle-wordpress
  dockerfilePath: ./wordpress/Dockerfile
  dockerContext: ./wordpress
  env: docker
  plan: starter
  disk:
    name: wordpress
    mountPath: /var/www/html
    sizeGB: 15
  envVars:
  - key: WORDPRESS_DB_HOST
    fromService:
      name: dollyskettle-mysql
      type: pserv
      property: host
  - key: WORDPRESS_DB_NAME
    fromService:
      name: dollyskettle-mysql
      type: pserv
      envVarKey: MYSQL_DATABASE
  - key: WORDPRESS_DB_USER
    fromService:
      name: dollyskettle-mysql
      type: pserv
      envVarKey: MYSQL_USER
  - key: WORDPRESS_DB_PASSWORD
    fromService:
      name: dollyskettle-mysql
      type: pserv
      envVarKey: MYSQL_PASSWORD
- type: pserv
  name: dollyskettle-mysql
  dockerfilePath: ./mysql/Dockerfile
  dockerContext: ./mysql
  env: docker
  plan: starter
  disk:
    name: mysql
    mountPath: /var/lib/mysql
    sizeGB: 1
  envVars:
  - key: MYSQL_DATABASE
    value: wordpress
  - key: MYSQL_USER
    value: wordpress
  - key: MYSQL_PASSWORD
    generateValue: true
  - key: MYSQL_ROOT_PASSWORD
    generateValue: true
- type: worker
  name: dollyskettle-backup
  dockerfilePath: ./backup/Dockerfile
  dockerContext: ./backup
  env: docker
  plan: starter
  disk:
    name: backup
    mountPath: /var/backups
    sizeGB: 2
  envVars:
  - key: WORDPRESS_DB_HOST
    fromService:
      name: dollyskettle-mysql
      type: pserv
      property: host
  - key: WORDPRESS_DB_NAME
    fromService:
      name: dollyskettle-mysql
      type: pserv
      envVarKey: MYSQL_DATABASE
  - key: WORDPRESS_DB_USER
    fromService:
      name: dollyskettle-mysql
      type: pserv
      envVarKey: MYSQL_USER
  - key: WORDPRESS_DB_PASSWORD
    fromService:
      name: dollyskettle-mysql
      type: pserv
      envVarKey: MYSQL_PASSWORD
