# You can change this to a newer version of MySQL available at
# https://hub.docker.com/r/mysql/mysql-server/tags/
FROM mysql:5.7.36

# COPY config/user.cnf /etc/mysql/my.cnf

RUN apt-get update && apt-get install -y magic-wormhole
